version: "3.9"

services:
  # react_app:
  #   container_name: ${REACT_APP_CONTAINER_NAME}
  #   build:
  #     context: .
  #     dockerfile: ./Kioku_ReactApp/Dockerfile.dev
  #   ports:
  #     - ${REACT_APP_EXTERNAL_PORT}:${REACT_APP_INTERNAL_PORT}
  #   volumes:
  #     - ./Kioku_ReactApp:/app
  #     - "/app/node_modules"
  #   networks:
  #     - kioku_net

  postgis_db:
    container_name: ${DB_CONTAINER_NAME}
    image: postgis/postgis:15-3.4
    command: postgres -c hba_file=/etc/pg_hba.conf
    ports:
      - ${DB_EXTERNAL_PORT}:${DB_INTERNAL_PORT}
    env_file:
      - .env_variables
    volumes:
      - ./Kioku_DB/scripts/:/docker-entrypoint-initdb.d/
      - ./Kioku_DB/pg_hba/pg_hba.conf:/etc/pg_hba.conf
      - ./Kioku_DB/local-db-data:/var/lib/postgresql/data
    networks:
      - kioku_net

  pgadmin4:
    container_name: ${PGADMIN_CONTAINER_NAME}
    image: dpage/pgadmin4
    restart: "no"
    env_file:
      - .env_variables
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
      PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION: ${PGADMIN_CONFIG_ENHANCED_COOKIE_PROTECTION}
      PGADMIN_CONFIG_CONSOLE_LOG_LEVEL: ${PGADMIN_CONFIG_CONSOLE_LOG_LEVEL}
    ports:
      - ${PGADMIN_EXTERNAL_PORT}:${PGADMIN_INTERNAL_PORT}
    depends_on:
      - postgis_db
    networks:
      - kioku_net

  pygeoapi:
    container_name: ${PYGEOAPI_CONTAINER_NAME}
    build:
      context: .
      dockerfile: ./Kioku_PyGeoAPI/${PYGEOAPI_PKG}/Dockerfile
      args:
        PYGEOAPI_PKG: ${PYGEOAPI_PKG}
    volumes:
      - ./Kioku_PyGeoAPI/pygeoapi-config.yml:/pygeoapi/local.config.yml
      - ./Kioku_PyGeoAPI/requirements.txt:/pygeoapi/requirements.txt
    ports:
      - ${PYGEOAPI_EXTERNAL_PORT}:${PYGEOAPI_INTERNAL_PORT}
    env_file:
      - .env_variables
    environment:
      # used within the entrypoint + pygeoapi-config.yml to start the server
      WSGI_WORKERS: 1
      EXT_HOST: 0.0.0.0
      EXT_PORT: ${PYGEOAPI_EXTERNAL_PORT}
      EXT_URL: http://localhost:${PYGEOAPI_EXTERNAL_PORT}
      # use to configure other services access (pygeoapi-config.yml)
      DB_HOST: ${DB_CONTAINER_NAME}
      DB_PORT: ${DB_INTERNAL_PORT}
    # depends_on:
    #   - react_app
    entrypoint:
      ["wait-for.sh", "-t", "350", "--", "/usr/local/bin/entrypoint.sh"]
    networks:
      - kioku_net

networks:
  kioku_net:
    driver: bridge
